package window;

import config.ConfigManager35;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Control;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

// This class is responsible for actually displaying the elements generated by the ConfigManager
public class WindowManager35 extends Application {
    // Window Resolution and Titles are set here
    private final static int width = 970;
    private final static int height = 600;
    private final static String title = "Assignment 3";

    // Called by the start() method to add the elements to the pane's children
    private void loadUI(ConfigManager35 configManager, Pane pane){
        configManager.execute();
        while(configManager.hasMoreItems()){
            Control element = configManager.nextElement();
            pane.getChildren().add(element);
        }
    }

    // Methods required to be overridden by JavaFX
    @Override
    public void start(Stage stage) throws Exception {
        ConfigManager35 configManager = ConfigManager35.getInstance();
        Pane pane = new Pane();
        loadUI(configManager, pane);
        Scene scene=new Scene(pane,width,height);
        stage.setTitle(title);
        stage.setScene(scene);
        stage.show();
    }

    public void execute(String[] args){
        launch(args);
    }
}