import config.ConfigManager35;
import factory.HighDetailedFactory35;
import factory.SimplisticFactory35;
import window.WindowManager35;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.InputMismatchException;
import java.util.Scanner;

// The main starter class
public class Main35 {
    // Config file names
    private final static String CONFIG_FILE_NAME_TEXT = "config.txt";
    private final static String CONFIG_FILE_NAME_XML = "config.xml";

    public static void main(String[] args) {
        // The window generated by JavaFX usually runs synchronously. Thus it is run on a thread to avoid program blocking
        Thread guiThread = new Thread(new Runnable() {
            @Override
            public void run() {
                WindowManager35 windowManager = new WindowManager35();
                windowManager.execute(args);
            }
        });

        // Take user prompts
        while(true) {
            try {
                System.out.println("Select your config file:");
                System.out.println("1. config.txt");
                System.out.println("2. config.xml");

                int configType;
                Scanner sc = new Scanner(System.in);
                configType = sc.nextInt();

                if (configType == 1) {
                    File file = new File(CONFIG_FILE_NAME_TEXT);
                    if(!file.isFile())
                        throw new FileNotFoundException("\"config.txt\" does not exist in the application root directory. Please make sure the file exists\n");
                    ConfigManager35.getInstance().setFileName(CONFIG_FILE_NAME_TEXT);

                    // 1 is Simplistic, 2 is High Detailed
                    if(selectDesignStyle() == 1){
                        ConfigManager35.getInstance().setFactory(new SimplisticFactory35());
                    }
                    else{
                        ConfigManager35.getInstance().setFactory(new HighDetailedFactory35());
                    }
                    guiThread.start();
                    break;
                } else if (configType == 2) {
                    File file = new File(CONFIG_FILE_NAME_TEXT);
                    if(!file.isFile())
                        throw new FileNotFoundException("\"config.xml\" does not exist in the application root directory. Please make sure the file exists\n");

                    ConfigManager35.getInstance().setFileName(CONFIG_FILE_NAME_XML);

                    // 1 is Simplistic, 2 is High Detailed
                    if(selectDesignStyle() == 1){
                        ConfigManager35.getInstance().setFactory(new SimplisticFactory35());
                    }
                    else{
                        ConfigManager35.getInstance().setFactory(new HighDetailedFactory35());
                    }
                    guiThread.start();

                    break;
                }
            } catch (FileNotFoundException exception){
                System.out.println(exception.getMessage());
            }
        }

    }

    // User prompt to select design style
    private static int selectDesignStyle() {
        while(true) {
            try {
                System.out.println("Please select your preferred style:");
                System.out.println("1. Simplistic");
                System.out.println("2. High Detailed");

                Scanner sc = new Scanner(System.in);
                int choice = sc.nextInt();
                if(choice != 1 && choice != 2)
                    throw new InputMismatchException("Please enter a valid number");

                return choice;
            } catch (InputMismatchException exception){
                System.out.println(exception.getMessage() + "\n");
            }
        }
    }
}
